<?php

namespace Common\Helpers;

use Common\Helpers\Curls\TradingView\TradingViewCurl;
use WebSocket\Client;
use WebSocket\ConnectionException;

class TradingViewWebsocket
{
    public $tickerData;
    private $session;
    private $subscriptions;
    private $websocket;
    public $sessionRegistered;
    private $class;
    private $login;
    private $password;
    public $closeSocket = false;

    /**
     * TradingViewWebsocket constructor.
     * @param $ticker
     * @param $func
     * @param null $login
     * @param null $password
     */
    public function __construct($func, $ticker, $login = null, $password = null)
    {
        $this->count = 0;
        $this->ticker = $ticker;
        $this->login = $login;
        $this->password = $password;
        $this->func = $func;
        $this->resetWebSocket();
    }

    /**
     * @param $func
     * @param $ticker
     * @param null $login
     * @param null $password
     */
    public static function create($func, $ticker, $login = null, $password = null)
    {
        new self($func, $ticker, $login, $password);
    }

    private function generateSession()
    {
        return "qs_" . $this->generateRandomString(12);
    }

    function generateRandomString($length = 10)
    {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }

    private function sendMessage($func, $args)
    {
        $this->websocket->send($this->createMessage($func, $args));
    }

    public function registerTicker($ticker)
    {
        if (is_array($ticker)) {
            foreach ($ticker as $symbol)
            {
                $this->subscriptions[] = $symbol;
                $this->websocket->send($this->createMessage("quote_add_symbols", [$this->session, $symbol, ['flags' => ["force_permission"]]]));
            }
        }else {
            $this->subscriptions[] = $ticker;
            $this->websocket->send($this->createMessage("quote_add_symbols", [$this->session, $ticker, ['flags' => ["force_permission"]]]));
        }
    }

    public function unregisterTicker($ticker)
    {
        $index = array_search($ticker, $this->subscriptions);
        if ($index === false) {
            return;
        }
        unset($this->subscriptions[$index]);
        sort($this->subscriptions);
    }

    public function resetWebSocket()
    {
        $this->tickerData = [];
        $this->subscriptions = [];
        $this->session = $this->generateSession();
        $this->sessionRegistered = false;
        if ($this->login and $this->password) {
            $wss = "wss://prodata.tradingview.com/socket.io/websocket";
        } else {
            $wss = "wss://data.tradingview.com/socket.io/websocket";
        }
        $this->websocket = new Client(
            $wss,
            [
                'timeout' => 60, // 1 minute time out
                'headers' => [
                    'Origin' => 'https://data.tradingview.com',
                ],
            ]
        );
        while (true) {
            if ($this->closeSocket) {
                break;
            }
            try {
                $string = $this->websocket->receive();
                $packets = $this->parseMessages($string);
                foreach ($packets as $packet) {
                    if (is_array($packet) && $packet["~protocol~keepalive~"]) {
                        $this->sendRawMessage("~h~" . $packet["~protocol~keepalive~"]);
                    } elseif (isset($packet->session_id)) {
                        if ($this->login && $this->password) {
                            $request_headers = [
                                "accept: */*",
                                "accept-encoding: gzip, deflate, br",
                                "accept-language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,lt;q=0.6",
                                "cache-control: no-cache",
                                "content-type: application/x-www-form-urlencoded",
                                "origin: https://www.tradingview.com",
                                "pragma: no-cache",
                                "referer: no-cache",
                                "sec-fetch-dest: empty",
                                "sec-fetch-mode: cors",
                                "sec-fetch-site: same-origin",
                                "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
                                "x-language: en",
                                "x-requested-with: XMLHttpRequest"
                            ];
                            $ch = curl_init();
                            curl_setopt($ch, CURLOPT_POST, true);
                            curl_setopt($ch, CURLOPT_URL, "https://www.tradingview.com/accounts/signin/");
                            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
                            curl_setopt($ch, CURLOPT_COOKIEFILE, __DIR__ . '/cookie.txt');
                            curl_setopt($ch, CURLOPT_COOKIEJAR, __DIR__ . '/cookie.txt');
                            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
                            curl_setopt($ch, CURLOPT_HTTPHEADER, $request_headers);
                            curl_setopt($ch, CURLOPT_ENCODING, "gzip");
                            curl_setopt($ch, CURLOPT_POSTFIELDS, "feature_source=Header&username=$this->login&password=$this->password&remember=on");
                            $curl_exec = curl_exec($ch);
                            curl_close($ch);
                            $json = json_decode($curl_exec);
                            $auth_token = $json->user->auth_token;
                            $this->sendMessage("set_auth_token", [$auth_token]);
                        } else {
                            $this->sendMessage("set_auth_token", ["unauthorized_user_token"]);
                        }
                        $this->sendMessage("quote_create_session", [$this->session]);
                        $this->sendMessage(
                            "quote_set_fields",
                            [
                                $this->session,
                                'accounts_payable_fq',
                                'accounts_payable_fq_h',
                                'accounts_payable_fy',
                                'accounts_payable_fy_h',
                                'accounts_receivables_net_fq_h',
                                'accounts_receivables_net_fy_h',
                                'accrued_expenses_fy',
                                'accrued_expenses_fy_h',
                                'accrued_payroll_fq_h',
                                'accrued_payroll_fy_h',
                                'accum_deprec_total_fq_h',
                                'accum_deprec_total_fy_h',
                                'additional_paid_in_capital_fq',
                                'additional_paid_in_capital_fq_h',
                                'additional_paid_in_capital_fy',
                                'additional_paid_in_capital_fy_h',
                                'adjustment',
                                'after_tax_margin',
                                'after_tax_other_income_fq',
                                'after_tax_other_income_fq_h',
                                'after_tax_other_income_fy',
                                'after_tax_other_income_fy_h',
                                'after_tax_other_income_ttm',
                                'all_time_high',
                                'all_time_low',
                                'allowed_adjustment',
                                'alor',
                                'cost_of_goods_excl_dep_amort_ttm',
                                'alt_prefixes',
                                'amortization_fq_h',
                                'amortization_fy_h',
                                'amount_recent',
                                'asset_turnover_current',
                                'asset_turnover_fq',
                                'asset_turnover_fq_h',
                                'asset_turnover_fy',
                                'asset_turnover_fy_h',
                                'average_volume',
                                'basic_eps_net_income',
                                'basic_shares_outstanding_fq',
                                'basic_shares_outstanding_fq_h',
                                'basic_shares_outstanding_fy',
                                'basic_shares_outstanding_fy_h',
                                'beta_1_year',
                                'beta_3_year',
                                'beta_5_year',
                                'book_per_share_fq',
                                'book_per_share_fy',
                                'book_tangible_per_share_fq',
                                'book_tangible_per_share_fy',
                                'book_value_per_share_fq',
                                'book_value_per_share_fq_h',
                                'book_value_per_share_fy',
                                'book_value_per_share_fy_h',
                                'broker_names',
                                'business_description',
                                'capital_expenditures_fixed_assets_fq',
                                'capital_expenditures_fixed_assets_fq_h',
                                'capital_expenditures_fixed_assets_fy',
                                'capital_expenditures_fixed_assets_fy_h',
                                'capital_expenditures_fixed_assets_ttm',
                                'capital_expenditures_fq',
                                'capital_expenditures_fq_h',
                                'capital_expenditures_fy',
                                'capital_expenditures_fy_h',
                                'capital_expenditures_other_assets_fq',
                                'capital_expenditures_other_assets_fq_h',
                                'capital_expenditures_other_assets_',
                                'capital_expenditures_other_assets_fy',
                                'capital_expenditures_other_assets_fy_h',
                                'capital_expenditures_other_assets_ttm',
                                'capital_expenditures_ttm',
                                'capital_lease_obligations_fq',
                                'capital_lease_obligations_fq_h',
                                'capital_lease_obligations_fy',
                                'capital_lease_obligations_fy_h',
                                'capital_operating_lease_obligations_fq',
                                'capital_operating_lease_obligations_fq_h',
                                'capital_operating_lease_obligations_fy',
                                'capital_operating_lease_obligations_fy_h',
                                'cash_f_financing_activities_fq',
                                'cash_f_financing_activities_fq_h',
                                'cash_f_financing_activities_fy',
                                'cash_f_financing_activities_fy_h',
                                'cash_f_financing_activities_ttm',
                                'cash_f_investing_activities_fq',
                                'cash_f_investing_activities_fq_h',
                                'cash_f_investing_activities_fy',
                                'cash_f_investing_activities_fy_h',
                                'cash_f_investing_activities_ttm',
                                'cash_f_operating_activities_fq',
                                'cash_f_operating_activities_fq_h',
                                'cash_f_operating_activities_fy',
                                'cash_f_operating_activities_fy_h',
                                'cash_f_operating_activities_ttm',
                                'cash_flow_deferred_taxes_fq_h',
                                'cash_flow_deferred_taxes_fy_h',
                                'cash_flow_deprecation_n_amortization_fq_h',
                                'cash_flow_deprecation_n_amortization_fy_h',
                                'cash_n_equivalents_fq_h',
                                'cash_n_equivalents_fy_h',
                                'cash_n_short_term_invest_fq_h',
                                'cash_n_short_term_invest_fy_h',
                                'change_in_accounts_payable_fq_h',
                                'change_in_accounts_payable_fy_h',
                                'change_in_accounts_receivable_fq_h',
                                'change_in_accounts_receivable_fy_h',
                                'change_in_accrued_expenses_fq_h',
                                'change_in_accrued_expenses_fy_h',
                                'change_in_inventories_fq_h',
                                'change_in_inventories_fy_h',
                                'change_in_other_assets_fq_h',
                                'change_in_other_assets_fy_h',
                                'change_in_taxes_payable_fq_h',
                                'change_in_taxes_payable_fy_h',
                                'changes_in_working_capital_fq',
                                'changes_in_working_capital_fq_h',
                                'changes_in_working_capital_fy',
                                'changes_in_working_capital_fy_h',
                                'changes_in_working_capital_ttm',
                                'close',
                                'common_dividends_cash_flow_fq',
                                'common_dividends_cash_flow_fq_h',
                                'common_dividends_cash_flow_fy',
                                'common_dividends_cash_flow_fy_h',
                                'common_dividends_cash_flow_ttm',
                                'common_equity_total_fq',
                                'common_equity_total_fq_h',
                                'common_equity_total_fy',
                                'common_equity_total_fy_h',
                                'common_stock_par_fq',
                                'common_stock_par_fq_h',
                                'common_stock_par_fy',
                                'common_stock_par_fy_h',
                                'cost_of_goods_excl_dep_amort_fq',
                                'cost_of_goods_excl_dep_amort_fq_h',
                                'cost_of_goods_excl_dep_amort_fy_h',
                                'cost_of_goods_excl_dep_amort_fy',
                                'cost_of_goods_fq_h',
                                'cost_of_goods_fy_h',
                                'country',
                                'country_fund',
                                'currency',
                                'currency_fund',
                                'currency_id',
                                'current_port_debt_capital_leases_fq_h',
                                'current_port_debt_capital_leases_fy_h',
                                'current_ratio',
                                'current_ratio_current',
                                'current_ratio_fq',
                                'current_ratio_fq_h',
                                'current_ratio_fy',
                                'current_ratio_fy_h',
                                'daily_bar',
                                'timezone',
                                'subsessions',
                                'daily_confirm_offset',
                                'data_update_time',
                                'debt_to_asset_current',
                                'debt_to_asset_fq',
                                'debt_to_asset_fq_h',
                                'debt_to_asset_fy',
                                'debt_to_asset_fy_h',
                                'debt_to_equity',
                                'debt_to_equity_current',
                                'debt_to_equity_fq',
                                'debt_to_equity_fq_h',
                                'debt_to_equity_fy',
                                'debt_to_equity_fy_h',
                                'deferred_income_current_fq',
                                'deferred_income_current_fq_h',
                                'deferred_income_current_fy',
                                'deferred_income_current_fy_h',
                                'deferred_income_non_current_fq',
                                'deferred_income_non_current_fq_h',
                                'deferred_income_non_current_fy',
                                'deferred_tax_assests_fq',
                                'deferred_tax_assests_fq_h',
                                'deferred_tax_assests_fy',
                                'deferred_tax_assests_fy_h',
                                'deferred_tax_liabilities_fq',
                                'deferred_tax_liabilities_fq_h',
                                'deferred_tax_liabilities_fy',
                                'deferred_tax_liabilities_fy_h',
                                'dep_amort_exp_income_s_fq',
                                'dep_amort_exp_income_s_fq_h',
                                'dep_amort_exp_income_s_fy',
                                'dep_amort_exp_income_s_fy_h',
                                'dep_amort_exp_income_s_ttm',
                                'depreciation_depletion_fq_h',
                                'depreciation_depletion_fy',
                                'depreciation_depletion_fy_h',
                                'depreciation_depletion_ttm',
                                'diluted_net_income_fq',
                                'diluted_net_income_fq_h',
                                'diluted_net_income_fy',
                                'diluted_net_income_fy_h',
                                'diluted_net_income_ttm',
                                'diluted_shares_outstanding_fq',
                                'diluted_shares_outstanding_fq_h',
                                'diluted_shares_outstanding_fy',
                                'diluted_shares_outstanding_fy_h',
                                'dilution_adjustment_fq',
                                'dilution_adjustment_fq_h',
                                'dilution_adjustment_fy',
                                'dilution_adjustment_fy_h',
                                'dilution_adjustment_ttm',
                                'discontinued_operations_fq',
                                'discontinued_operations_fq_h',
                                'discontinued_operations_fy',
                                'discontinued_operations_fy_h',
                                'discontinued_operations_ttm',
                                'dividend_amount_net_recent',
                                'dividend_amount_recent',
                                'dividend_ex_date_recent',
                                'dividend_frequency_recent',
                                'dividend_payment_date_recent',
                                'dividend_payout_ratio_fq_h',
                                'dividend_payout_ratio_fy',
                                'dividend_payout_ratio_fy_h',
                                'dividend_payout_ratio_percent_fy',
                                'dividend_type_recent',
                                'dividends_paid',
                                'dividends_payable_fy',
                                'dividends_payable_fy_h',
                                'dividends_yield',
                                'dividends_yield_fq_h',
                                'dividends_yield_fy',
                                'dividends_yield_fy_h',
                                'dps_common_stock_prim_issue_fq_h',
                                'dps_common_stock_prim_issue_fy',
                                'dps_common_stock_prim_issue_fy_h',
                                'earnings_fiscal_period_fq',
                                'earnings_fiscal_period_fq_h',
                                'earnings_per_share_basic_fq',
                                'earnings_per_share_basic_fq_h',
                                'earnings_per_share_basic_fy',
                                'earnings_per_share_basic_fy_h',
                                'earnings_per_share_basic_ttm',
                                'earnings_per_share_diluted_fq',
                                'earnings_per_share_diluted_fq_h',
                                'earnings_per_share_diluted_fy',
                                'earnings_per_share_diluted_fy_h',
                                'earnings_per_share_diluted_ttm',
                                'earnings_per_share_forecast_details_fq',
                                'earnings_per_share_forecast_details_fq_h',
                                'earnings_per_share_forecast_details_fy',
                                'earnings_per_share_forecast_details_fy_h',
                                'earnings_per_share_forecast_fq',
                                'earnings_per_share_forecast_fq_h',
                                'earnings_per_share_forecast_next_details_fq',
                                'earnings_per_share_forecast_next_details_fy',
                                'earnings_per_share_forecast_next_fq',
                                'earnings_per_share_forecast_next_fy',
                                'earnings_per_share_fq',
                                'earnings_per_share_fq_h',
                                'earnings_per_share_ttm',
                                'earnings_release_calendar_date',
                                'earnings_release_date',
                                'earnings_release_date_h',
                                'earnings_release_next_date',
                                'earnings_release_next_time',
                                'earnings_release_time',
                                'ebit_fq_h',
                                'ebit_fy_h',
                                'ebitda_fq_h',
                                'ebitda_fy_h',
                                'ebitda_margin_fq_h',
                                'ebitda_margin_fy_h',
                                'enterprise_value_current',
                                'enterprise_value_ebitda_fq_h',
                                'enterprise_value_ebitda_fy_h',
                                'enterprise_value_fq',
                                'enterprise_value_fq_h',
                                'enterprise_value_fy',
                                'enterprise_value_fy_h',
                                'eps_diluted_growth_percent_fq',
                                'eps_diluted_growth_percent_fy',
                                'equity_in_earnings_fq',
                                'equity_in_earnings_fq_h',
                                'equity_in_earnings_fy',
                                'equity_in_earnings_fy_h',
                                'equity_in_earnings_ttm',
                                'ex_date_recent',
                                'ex_dividend_date_recent',
                                'listed_exchange',
                                'original_name',
                                'lp',
                                'exchange',
                                'exchange_listed_symbol',
                                'exchange_ticker',
                                'exchange_traded',
                                'feed_has_dwm',
                                'feed_has_intraday',
                                'feed_ticker',
                                'fiscal_period_end_fq',
                                'fiscal_period_end_fq_h',
                                'fiscal_period_end_fy',
                                'fiscal_period_end_fy_h',
                                'fiscal_period_fq',
                                'fiscal_period_fq_h',
                                'fiscal_period_fy',
                                'fiscal_period_fy_h',
                                'float_shares_outstanding',
                                'float_shares_outstanding_current',
                                'float_shares_outstanding_fy',
                                'float_shares_outstanding_fy_h',
                                'founded',
                                'free_cash_flow',
                                'free_cash_flow_fq',
                                'free_cash_flow_fq_h',
                                'free_cash_flow_fy',
                                'free_cash_flow_fy_h',
                                'free_cash_flow_per_share_fq',
                                'free_cash_flow_per_share_fq_h',
                                'free_cash_flow_per_share_fy',
                                'free_cash_flow_per_share_fy_h',
                                'free_cash_flow_ttm',
                                'frequency_recent',
                                'fundamental_currency_code',
                                'fundamental_data',
                                'funds_f_operations_fq',
                                'funds_f_operations_fq_h',
                                'funds_f_operations_fy',
                                'funds_f_operations_fy_h',
                                'funds_f_operations_ttm',
                                'goodwill',
                                'goodwill_fq',
                                'goodwill_fq_h',
                                'goodwill_fy',
                                'goodwill_fy_h',
                                'gross_margin_fq_h',
                                'gross_margin_fy_h',
                                'gross_profit_fq_h',
                                'gross_profit_fy_h',
                                'group',
                                'has_adjustment',
                                'has_depth',
                                'has_dwm',
                                'has_intraday',
                                'has_no_realtime',
                                'has_no_volume',
                                'has_price_snapshot',
                                'high',
                                'history_tag',
                                'ibkr',
                                'income_tax_fq',
                                'income_tax_fq_h',
                                'income_tax_fy',
                                'income_tax_fy_h',
                                'income_tax_payable_fq_h',
                                'income_tax_payable_fy_h',
                                'income_tax_ttm',
                                'industry',
                                'industry_i18n_en',
                                'intangibles_net_fq',
                                'intangibles_net_fq_h',
                                'intangibles_net_fy',
                                'intangibles_net_fy_h',
                                'interest_capitalized_fq',
                                'interest_capitalized_fq_h',
                                'interest_capitalized_fy',
                                'interest_capitalized_fy_h',
                                'interest_capitalized_ttm',
                                'interest_expense_on_debt_fq_h',
                                'interest_expense_on_debt_fy',
                                'interest_expense_on_debt_fy_h',
                                'interest_expense_on_debt_ttm',
                                'invent_turnover_fq_h',
                                'invent_turnover_fy_h',
                                'inventory_finished_goods_fq_h',
                                'inventory_finished_goods_fy_h',
                                'inventory_progress_payments_fq_h',
                                'inventory_progress_payments_fy_h',
                                'inventory_raw_materials_fq_h',
                                'inventory_raw_materials_fy_h',
                                'inventory_work_in_progress_fq_h',
                                'inventory_work_in_progress_fy_h',
                                'investments_in_unconcsolidate_fq',
                                'investments_in_unconcsolidate_fq_h',
                                'investments_in_unconcsolidate_fy',
                                'investments_in_unconcsolidate_fy_h',
                                'is_next_earnings_release_date_estimated',
                                'is_replayable',
                                'issuance_of_debt_net_fq',
                                'issuance_of_debt_net_fq_h',
                                'issuance_of_debt_net_fy',
                                'issuance_of_debt_net_fy_h',
                                'issuance_of_debt_net_ttm',
                                'issuance_of_long_term_debt_fq',
                                'issuance_of_long_term_debt_fy',
                                'issuance_of_long_term_debt_fy_h',
                                'issuance_of_other_debt_fq',
                                'issuance_of_other_debt_fq_h',
                                'issuance_of_other_debt_fy',
                                'issuance_of_other_debt_fy_h',
                                'issuance_of_short_term_debt_fq',
                                'issuance_of_short_term_debt_fq_h',
                                'issuance_of_short_term_debt_fy',
                                'issuance_of_short_term_debt_fy_h',
                                'issuance_of_short_term_debt_ttm',
                                'issuance_of_stock_net_fq',
                                'issuance_of_stock_net_fq_h',
                                'issuance_of_stock_net_fy',
                                'issuance_of_stock_net_fy_h',
                                'issuance_of_stock_net_ttm',
                                'is_tradable',
                                'kind_delay',
                                'last_annual_eps',
                                'last_annual_revenue',
                                'local_code',
                                'local_description',
                                'location',
                                'long_term_debt_excl_capital_lease_fq',
                                'long_term_debt_excl_capital_lease_fq_h',
                                'long_term_debt_excl_capital_lease_fy',
                                'long_term_debt_excl_capital_lease_fy_h',
                                'long_term_debt_fq',
                                'long_term_debt_fq_h',
                                'long_term_debt_fy',
                                'long_term_debt_fy_h',
                                'long_term_debt_to_assets_current',
                                'long_term_debt_to_assets_fq',
                                'long_term_debt_to_assets_fq_h',
                                'long_term_debt_to_assets_fy',
                                'long_term_debt_to_assets_fy_h',
                                'long_term_debt_to_equity_fq',
                                'long_term_investments_fq',
                                'long_term_investments_fq_h',
                                'long_term_investments_fy',
                                'long_term_investments_fy_h',
                                'long_term_note_receivable_fq_h',
                                'long_term_note_receivable_fy_h',
                                'long_term_other_assets_total_fq',
                                'long_term_other_assets_total_fq_h',
                                'long_term_other_assets_total_fy',
                                'long_term_other_assets_total_fy_h',
                                'low',
                                'market_cap_basic',
                                'market_cap_basic_current',
                                'market_cap_basic_fq',
                                'market_cap_basic_fq_h',
                                'market_cap_basic_fy',
                                'market_cap_basic_fy_h',
                                'market_status',
                                'mic',
                                'minmovement',
                                'minmovement2',
                                'minority_interest_exp_fq',
                                'minority_interest_exp_fq_h',
                                'minority_interest_exp_fy',
                                'minority_interest_exp_fy_h',
                                'minority_interest_exp_ttm',
                                'minority_interest_fq',
                                'minority_interest_fq_h',
                                'minority_interest_fy',
                                'minority_interest_fy_h',
                                'minute_bar',
                                'MOEX_DLY',
                                'net_debt',
                                'net_debt_fq',
                                'net_debt_fy',
                                'net_debt_fy_h',
                                'net_income',
                                'net_income_bef_disc_oper_fq',
                                'net_income_bef_disc_oper_fq_h',
                                'net_income_bef_disc_oper_fy',
                                'net_income_bef_disc_oper_fy_h',
                                'net_income_bef_disc_oper_ttm',
                                'net_income_fq',
                                'net_income_fq_h',
                                'net_income_fy',
                                'net_income_fy_h',
                                'net_income_starting_line_fq_h',
                                'net_income_starting_line_fy_h',
                                'net_income_ttm',
                                'net_margin',
                                'net_margin_current',
                                'net_margin_fq',
                                'net_margin_fq_h',
                                'net_margin_fy',
                                'net_margin_fy_h',
                                'net_margin_ttm',
                                'next_earnings_fiscal_period_fq',
                                'next_fiscal_period_fq',
                                'next_fiscal_period_fy',
                                'non_cash_items_fq_h',
                                'non_cash_items_fy_h',
                                'non_oper_income_fq',
                                'non_oper_income_fq_h',
                                'non_oper_income_fy',
                                'non_oper_income_fy_h',
                                'non_oper_income_ttm',
                                'non_oper_interest_exp_fq',
                                'non_oper_interest_exp_fq_h',
                                'non_oper_interest_exp_fy',
                                'non_oper_interest_exp_fy_h',
                                'non_oper_interest_exp_ttm',
                                'non_oper_interest_income_fq_h',
                                'non_oper_interest_income_fy_h',
                                'notes_payable_short_term_debt_fy_h',
                                'notes_payable_short_term_debt_fq_h',
                                'other_short_term_debt_fq',
                                'other_short_term_debt_fq_h',
                                'dividends_payable_fq',
                                'dividends_payable_fq_h',
                                'number_of_employees',
                                'number_of_employees_fy',
                                'number_of_employees_fy_h',
                                'number_of_shareholders_fy_h',
                                'oper_income_fq',
                                'oper_income_fq_h',
                                'oper_income_fy',
                                'oper_income_fy_h',
                                'oper_income_ttm',
                                'operating_cash_flow_per_share',
                                'operating_expenses_fq',
                                'operating_expenses_fq_h',
                                'operating_expenses_fy',
                                'operating_expenses_fy_h',
                                'operating_expenses_ttm',
                                'operating_lease_liabilities_fq_h',
                                'operating_lease_liabilities_fy_h',
                                'operating_margin',
                                'operating_margin_current',
                                'operating_margin_fq',
                                'operating_margin_fq_h',
                                'operating_margin_fy',
                                'operating_margin_fy_h',
                                'operating_margin_ttm',
                                'other_common_equity_fq',
                                'other_common_equity_fq_h',
                                'other_common_equity_fy',
                                'other_common_equity_fy_h',
                                'other_current_assets_total_fq_h',
                                'other_current_assets_total_fy_h',
                                'other_current_liabilities_fq',
                                'other_current_liabilities_fq_h',
                                'other_current_liabilities_fy',
                                'other_current_liabilities_fy_h',
                                'other_financing_cash_flow_items_total_fq',
                                'other_financing_cash_flow_items_total_fq_h',
                                'other_financing_cash_flow_items_total_fy',
                                'other_financing_cash_flow_items_total_fy_h',
                                'other_financing_cash_flow_items_total_ttm',
                                'other_financing_cash_flow_sources_fq',
                                'other_financing_cash_flow_sources_fq_h',
                                'other_financing_cash_flow_sources_fy',
                                'other_financing_cash_flow_sources_ttm',
                                'other_financing_cash_flow_uses_fq',
                                'other_financing_cash_flow_uses_fy',
                                'other_financing_cash_flow_uses_fy_h',
                                'other_financing_cash_flow_uses_ttm',
                                'other_income_fq',
                                'other_income_fq_h',
                                'other_income_fy',
                                'other_income_fy_h',
                                'other_income_ttm',
                                'other_intangibles_net_fq',
                                'other_intangibles_net_fq_h',
                                'other_intangibles_net_fy',
                                'other_intangibles_net_fy_h',
                                'other_investing_cash_flow_items_total_fq',
                                'other_investing_cash_flow_items_total_fq_h',
                                'other_investing_cash_flow_items_total_fy',
                                'other_investing_cash_flow_items_total_fy_h',
                                'other_investing_cash_flow_items_total_ttm',
                                'other_investing_cash_flow_sources_fq',
                                'other_investing_cash_flow_sources_fq_h',
                                'other_investing_cash_flow_sources_fy',
                                'other_investing_cash_flow_sources_ttm',
                                'other_investing_cash_flow_uses_fq',
                                'other_investing_cash_flow_uses_fq_h',
                                'other_investing_cash_flow_uses_fy',
                                'other_investing_cash_flow_uses_fy_h',
                                'other_investing_cash_flow_uses_ttm',
                                'other_investments_fq',
                                'other_investments_fq_h',
                                'other_investments_fy',
                                'other_investments_fy_h',
                                'other_liabilities_total_fq',
                                'other_liabilities_total_fq_h',
                                'other_liabilities_total_fy',
                                'other_liabilities_total_fy_h',
                                'other_oper_expense_total_fq',
                                'other_oper_expense_total_fq_h',
                                'other_oper_expense_total_fy',
                                'other_oper_expense_total_fy_h',
                                'other_oper_expense_total_ttm',
                                'other_receivables_fq_h',
                                'other_short_term_debt_fy',
                                'other_short_term_debt_fy_h',
                                'paid_in_capital_fq',
                                'paid_in_capital_fq_h',
                                'paid_in_capital_fy',
                                'paid_in_capital_fy_h',
                                'payment_date_recent',
                                'popularity_rank',
                                'ppe_total_gross_fq_h',
                                'ppe_total_gross_fy_h',
                                'ppe_total_net_fq',
                                'ppe_total_net_fq_h',
                                'ppe_total_net_fy',
                                'ppe_total_net_fy_h',
                                'pre_tax_margin',
                                'pre_tax_margin_current',
                                'pre_tax_margin_fq',
                                'pre_tax_margin_fq_h',
                                'pre_tax_margin_fy',
                                'pre_tax_margin_fy_h',
                                'pre_tax_margin_ttm',
                                'preferred_dividends_cash_flow_fq_h',
                                'preferred_dividends_cash_flow_fy_h',
                                'preferred_dividends_cash_flow_ttm',
                                'preferred_dividends_fq',
                                'preferred_dividends_fq_h',
                                'preferred_dividends_fy',
                                'preferred_dividends_fy_h',
                                'preferred_dividends_ttm',
                                'preferred_stock_carrying_value_fq',
                                'preferred_stock_carrying_value_fq_h',
                                'preferred_stock_carrying_value_fy',
                                'preferred_stock_carrying_value_fy_h',
                                'prepaid_expenses_fq_h',
                                'prepaid_expenses_fy_h',
                                'pretax_equity_in_earnings_fq_h',
                                'pretax_equity_in_earnings_fy_h',
                                'pretax_income_fq',
                                'pretax_income_fq_h',
                                'pretax_income_fy',
                                'pretax_income_fy_h',
                                'pretax_income_ttm',
                                'prev_daily_bar',
                                'price_52_week_high',
                                'price_52_week_low',
                                'price_annual_book',
                                'price_annual_sales',
                                'price_book_current',
                                'price_book_fq',
                                'price_book_fq_h',
                                'price_book_fy',
                                'price_book_fy_h',
                                'price_book_ratio',
                                'price_cash_flow_current',
                                'price_cash_flow_fq',
                                'price_cash_flow_fq_h',
                                'price_cash_flow_fy',
                                'price_cash_flow_fy_h',
                                'price_earnings',
                                'price_earnings_current',
                                'price_earnings_forward_fy',
                                'price_earnings_fq',
                                'price_earnings_fq_h',
                                'price_earnings_fy',
                                'price_earnings_fy_h',
                                'price_earnings_ttm',
                                'price_free_cash_flow_current',
                                'price_free_cash_flow_ttm',
                                'price_percent_change_1_week',
                                'price_percent_change_52_week',
                                'price_revenue_ttm',
                                'price_sales_current',
                                'price_sales_fq',
                                'price_sales_fq_h',
                                'price_sales_fy',
                                'price_sales_fy_h',
                                'price_sales_ratio',
                                'price_target_average',
                                'price_target_high',
                                'price_target_low',
                                'price_target_median',
                                'pro_perm',
                                'provider_id',
                                'provision_f_risks_fq',
                                'provision_f_risks_fq_h',
                                'provision_f_risks_fy',
                                'provision_f_risks_fy_h',
                                'purchase_of_business_fq',
                                'purchase_of_business_fq_h',
                                'purchase_of_business_fy',
                                'purchase_of_business_fy_h',
                                'purchase_of_business_ttm',
                                'purchase_of_investments_fq',
                                'purchase_of_investments_fq_h',
                                'purchase_of_investments_fy',
                                'purchase_of_investments_fy_h',
                                'purchase_of_investments_ttm',
                                'purchase_of_stock_fq',
                                'purchase_of_stock_fq_h',
                                'purchase_of_stock_fy',
                                'purchase_of_stock_fy_h',
                                'purchase_of_stock_ttm',
                                'purchase_sale_business_fq',
                                'purchase_sale_business_fq_h',
                                'purchase_sale_business_fy',
                                'purchase_sale_business_fy_h',
                                'purchase_sale_business_ttm',
                                'purchase_sale_investments_fq',
                                'purchase_sale_investments_fq_h',
                                'purchase_sale_investments_fy',
                                'purchase_sale_investments_fy_h',
                                'purchase_sale_investments_ttm',
                                'quick_ratio_fq_h',
                                'quick_ratio_fy_h',
                                'rates_cf',
                                'rates_dividend_recent',
//                                'rates_earnings_next_fq',
//                                'rates_fq',
//                                'rates_fy',
//                                'rates_mc',
//                                'rates_pt',
//                                'rates_ttm',
                                'recommendation_buy',
                                'recommendation_hold',
                                'recommendation_mark',
                                'recommendation_over',
                                'recommendation_sell',
                                'recommendation_total',
                                'recommendation_under',
                                'reduction_of_long_term_debt_fq_h',
                                'reduction_of_long_term_debt_fy_h',
                                'region',
                                'research_and_dev_fq_h',
                                'research_and_dev_fy_h',
                                'retained_earnings_fq',
                                'retained_earnings_fq_h',
                                'retained_earnings_fy',
                                'retained_earnings_fy_h',
                                'return_of_invested_capital_percent_ttm',
                                'return_on_assets',
                                'return_on_assets_current',
                                'return_on_assets_fq',
                                'return_on_assets_fq_h',
                                'return_on_assets_fy',
                                'return_on_assets_fy_h',
                                'return_on_equity',
                                'return_on_equity_current',
                                'return_on_equity_fq',
                                'return_on_equity_fq_h',
                                'return_on_equity_fy',
                                'return_on_equity_fy_h',
                                'return_on_invested_capital',
                                'return_on_invested_capital_current',
                                'return_on_invested_capital_fq',
                                'return_on_invested_capital_fq_h',
                                'return_on_invested_capital_fy',
                                'return_on_invested_capital_fy_h',
                                'revenue_forecast_fq',
                                'revenue_forecast_fq_h',
                                'revenue_forecast_next_fq',
                                'revenue_fq',
                                'revenue_fq_h',
                                'revenue_per_employee',
                                'revenue_per_share_fy',
                                'revenue_per_share_ttm',
                                'rt_lag',
                                'rts_source',
                                'rt_update_time',
                                'sale_of_stock_fq',
                                'sale_of_stock_fq_h',
                                'sale_of_stock_fy',
                                'sale_of_stock_fy_h',
                                'sale_of_stock_ttm',
                                'sales_of_business_fq',
                                'sales_of_business_fq_h',
                                'sales_of_business_fy',
                                'sales_of_business_fy_h',
                                'sales_of_business_ttm',
                                'sales_of_investments_fq',
                                'sales_of_investments_fq_h',
                                'sales_of_investments_fy',
                                'sales_of_investments_fy_h',
                                'sector',
                                'sector-i18n',
                                'sell_gen_admin_exp_other_fq_h',
                                'sell_gen_admin_exp_other_fy_h',
                                'sell_gen_admin_exp_total_fq_h',
                                'sell_gen_admin_exp_total_fy_h',
                                'series_key',
                                'session-correction',
                                'session-display',
                                'session-extended',
                                'session-extended',
                                'session-extended',
                                'session-holidays',
                                'session-id',
                                'session-premarket',
                                'session-regular',
                                'session-regular',
                                'session-regular',
                                'short_term_debt_excl_current_port_fq_h',
                                'short_term_debt_excl_current_port_fy',
                                'short_term_debt_excl_current_port_fy_h',
                                'short_term_debt_fq',
                                'short_term_debt_fq_h',
                                'short_term_debt_fy',
                                'short_term_debt_fy_h',
                                'short_term_invest_fq_h',
                                'short_term_invest_fy_h',
                                'short_description',
                                'shrhldrs_equity_fq',
                                'shrhldrs_equity_fq_h',
                                'shrhldrs_equity_fy',
                                'shrhldrs_equity_fy_h',
                                'split_last_date',
                                'subsession_id',
                                'supplying_of_long_term_debt_fq',
                                'supplying_of_long_term_debt_fq_h',
                                'supplying_of_long_term_debt_fy',
                                'supplying_of_long_term_debt_fy_h',
                                'symbol',
                                'symbol_fullname',
                                'symbol_primaryname',
                                'symbol_proname',
                                'time',
                                'to_market',
                                'to_symbol',
                                'to_usd',
                                'total_assets',
                                'total_assets_fq',
                                'total_assets_fq_h',
                                'total_assets_fy',
                                'total_assets_fy_h',
                                'total_assets_h',
                                'total_cash_dividends_paid_fq',
                                'total_cash_dividends_paid_fq_h',
                                'total_cash_dividends_paid_fy',
                                'total_cash_dividends_paid_fy_h',
                                'total_cash_dividends_paid_ttm',
                                'total_current_assets',
                                'total_current_assets_fq',
                                'total_current_assets_fq_h',
                                'total_current_assets_fy',
                                'total_current_assets_fy_h',
                                'total_current_assets_h',
                                'total_current_liabilities_fq',
                                'total_current_liabilities_fq_h',
                                'total_current_liabilities_fy',
                                'total_current_liabilities_fy_h',
                                'total_debt',
                                'total_debt_fq',
                                'total_debt_fq_h',
                                'total_debt_fy',
                                'total_debt_fy_h',
                                'total_debt_h',
                                'total_equity_fq',
                                'total_equity_fq_h',
                                'total_equity_fy',
                                'total_equity_fy_h',
                                'total_extra_items_fq',
                                'total_extra_items_fq_h',
                                'total_extra_items_fy',
                                'total_extra_items_fy_h',
                                'total_extra_items_ttm',
                                'total_inventory_fq_h',
                                'total_inventory_fy_h',
                                'total_liabilities_fq',
                                'total_liabilities_fq_h',
                                'total_liabilities_fy',
                                'total_liabilities_fy_h',
                                'total_liabilities_shrhldrs_equity_fq',
                                'total_liabilities_shrhldrs_equity_fq_h',
                                'total_liabilities_shrhldrs_equity_fy',
                                'total_liabilities_shrhldrs_equity_fy_h',
                                'total_non_current_assets_fq',
                                'total_non_current_assets_fq_h',
                                'total_non_current_assets_fy',
                                'total_non_current_assets_fy_h',
                                'total_non_current_liabilities_fq',
                                'total_non_current_liabilities_fq_h',
                                'total_non_current_liabilities_fy',
                                'total_non_current_liabilities_fy_h',
                                'total_non_oper_income_fq',
                                'total_non_oper_income_fq_h',
                                'total_non_oper_income_fy',
                                'total_non_oper_income_fy_h',
                                'total_non_oper_income_ttm',
                                'total_oper_expense_fq',
                                'total_oper_expense_fq_h',
                                'total_oper_expense_fy',
                                'total_oper_expense_fy_h',
                                'total_oper_expense_ttm',
                                'total_receivables_net_fq_h',
                                'total_receivables_net_fy_h',
                                'total_revenue',
                                'total_revenue_fq',
                                'total_revenue_fq_h',
                                'total_revenue_fy',
                                'total_revenue_fy_h',
                                'total_revenue_h',
                                'total_revenue_ttm',
                                'total_shares_outstanding',
                                'total_shares_outstanding_calculated',
                                'total_shares_outstanding_current',
                                'total_shares_outstanding_fq',
                                'total_shares_outstanding_fq_h',
                                'total_shares_outstanding_fundamental',
                                'total_shares_outstanding_fy',
                                'total_shares_outstanding_fy_h',
                                'trade',
                                'trading_by',
                                'type',
                                'unit',
                                'pointvalue',
                                'description',
                                'treasury_stock_common_fq',
                                'treasury_stock_common_fq_h',
                                'treasury_stock_common_fy',
                                'type_recent',
                                'unusual_expense_inc_fq',
                                'unusual_expense_inc_fq_h',
                                'unusual_expense_inc_fy',
                                'unusual_expense_inc_fy_h',
                                'unusual_expense_inc_ttm',
                                'update_time',
                                'variable_tick_size',
                                'visible_plots_set',
                                'volume',
                                'deferred_income_non_current_fy_h',
                                'free_cash_flow_per_share_',
                                'other_financing_cash_flow_uses_fq_h',
                                'earnings_release_next_calendar_date',
                                'other_investing_cash_flow_sources_fy_h',
                                'funds_f_operations_',
                                'cash_f_operating_activities_',
                                'dividend_yield_recent',
                                'web_site_url',
                                'treasury_stock_common_fy_h',
//                                'rates_earnings_fq',
                                'amount_net_recent',
                                'deferred_income_non_current_',
                                'feed',
                                'interest_expense_on_debt_fq',
                                'issuance_of_long_term_debt_fq_h',
                                'popularity',
                                'non_oper_interest_exp_',
                                'other_receivables_fy_h',
                                'short_term_debt_excl_current_port_fq',
                                'other_financing_cash_flow_sources_fy_h',
                                'gross_profit_ttm',
                                'cost_of_goods_ttm',
                                'sell_gen_admin_exp_total_ttm',
                                'research_and_dev_ttm',
                                'sell_gen_admin_exp_other_ttm',
                                'non_oper_interest_income_ttm',
                                'pretax_equity_in_earnings_ttm',
                                'basic_shares_outstanding_ttm',
                                'diluted_shares_outstanding_ttm',
                                'ebitda_ttm',
//                                'ebit_ttm',
                                'cash_flow_deprecation_n_amortization_ttm',
                                'amortization_ttm',
                                'cash_flow_deferred_taxes_ttm',
                                'non_cash_items_ttm',
                                'change_in_accounts_receivable_ttm',
                                'change_in_taxes_payable_ttm',
                                'change_in_accounts_payable_ttm',
                                'change_in_accrued_expenses_ttm',
                                'change_in_inventories_ttm',
                                'change_in_other_assets_ttm',
                                'sales_of_investments_ttm',
                                'issuance_of_long_term_debt_ttm',
                                'supplying_of_long_term_debt_ttm',
                                'reduction_of_long_term_debt_ttm',
                                'issuance_of_other_debt_ttm',
                            ]
                        );
                        $this->sessionRegistered = true;
                        $this->registerTicker($this->ticker);
                    } elseif ($packet->m && $packet->m === "qsd" && isset($packet->p) && $packet->p[0] === $this->session) {
                        $tticker = $packet->p[1];
                        $tickerName = $tticker->n;
                        $tickerStatus = $tticker->s;

                        if ($tickerStatus !== 'ok') {
                            break;
                        }

                        $tickerUpdate = $tticker->v;

                        foreach ($tickerUpdate as $key => $value) {
                            $this->tickerData[$tickerName][$key] = $value;
                        }
                    }
                }
                if ($this->count > 1) {
                    break;
                }
                TradingViewCurl::readQuotes($this, $this->func, $this->ticker);
                $this->count++;
            } catch (ConnectionException $e) {
                LoggerHelper::getLogger('tradingview_socket')->error($e);
            }
        }
    }

    private function sendRawMessage($message)
    {
        $this->websocket->send($this->prependHeader($message));
    }

    // IO methods
    private function parseMessages($str)
    {
        $packets = [];
        $x = preg_split('/~m~(\d+)~m~/', $str);
        foreach ($x as $pack) {
            if (!strlen($pack)) continue;
            $pack = strrev($pack);
            $str = strpos($pack, "}");
            $pack = substr($pack, $str, strlen($pack));
            $pack = strrev($pack);
            if (strpos($pack, '~h~') !== false) {
                $packets[] = ["~protocol~keepalive~" => substr($pack, 3)];
            } else {
                $packets[] = json_decode($pack);
            }
        }
        return $packets;
    }

    private function prependHeader($str)
    {
        return "~m~" . strlen($str) . "~m~" . $str;
    }

    private function createMessage($func, $paramList)
    {
        return $this->prependHeader($this->constructMessage($func, $paramList));
    }

    private function constructMessage($func, $paramList)
    {
        return json_encode(
            [
                'm' => $func,
                'p' => $paramList
            ]
        );
    }
}